export * from './createNetwork'
export * from './createFirewallTcp'
export * from './createFirewallSsh'
export * from './createSubnet'
export * from './createConnector'
export * from './createRouter'
export * from './createFixIp'
export * from './createNat'
export * from './createIpRange'
export * from './connectVpc'
export * from './runVpcNat'

export const GCP_IP_RANGE = '10.124.0.0/28'
