export type { ChatCompletionMessageParam } from 'openai/resources'
export type { ChatCompletionChunk, ChatCompletion } from 'openai/resources/chat'
export { Stream } from 'openai/streaming'
export { generatePrompt } from './lib/genPrompt'
export { openAIChat, defaultOpenAIConfig } from './lib/openAIChat'
export { readOpenAIStream } from './lib/readOpenAIStream'
export { readGeminiStream } from './lib/readGeminiStream'
export { geminiChat, defaultGeminiConfig } from './lib/geminiChat'
export type { ConfigOpenAIType, OpenAIModel } from './lib/openAIChat'
export type { ConfigGeminiType, GeminiModel } from './lib/geminiChat'
export type { AIType, InputOutput } from './lib/genPrompt'
export type { Example } from './lib/types/skeetaiTypes'
export { NamingEnum, SkeetAiMode, InstanceType } from './lib/types/skeetaiTypes'
export { chat } from './lib/chat'
