#!/bin/bash

# Constants and configurable variables
NODE_VERSION=20.10.0

# This ensures the entire script is downloaded
{
set -e  # exit immediately if a command exits with a non-zero status

usage() {
    cat 1>&2 <<EOF
Custom Install Script
Installs nodenv, node $NODE_VERSION, and sets it as the global version.
Additionally, installs the @skeet-framework/cli package globally.

USAGE:
    custom-install-script.sh [FLAGS]

FLAGS:
    -h, --help              Prints help information
EOF
}

install_nodenv_and_node() {
    CURRENT_USER=$(whoami)
    USER_HOME=$(eval echo ~$CURRENT_USER)
    echo "Current user: $CURRENT_USER"
    echo "User home directory: $USER_HOME"

    PROFILE_PATH="$USER_HOME/.profile"
    if [[ $SHELL == */zsh ]]; then
        PROFILE_PATH="$USER_HOME/.zshrc"
    fi

    echo "Installing nodenv..."
    git clone https://github.com/nodenv/nodenv.git $USER_HOME/.nodenv
    echo 'export PATH="'$USER_HOME'/.nodenv/bin:$PATH"' >> $PROFILE_PATH
    echo 'eval "$('$USER_HOME'/.nodenv/bin/nodenv init -)"' >> $PROFILE_PATH
    . $PROFILE_PATH

    echo "Installing node-build..."
    git clone https://github.com/nodenv/node-build.git "$($USER_HOME/.nodenv/bin/nodenv root)"/plugins/node-build

    echo "Installing node $NODE_VERSION..."
    $USER_HOME/.nodenv/bin/nodenv install $NODE_VERSION
    $USER_HOME/.nodenv/bin/nodenv global $NODE_VERSION
    echo "Node installation completed!"

    echo "Installing @skeet-framework/cli..."
    npm i -g @skeet-framework/cli

    echo "Sourcing $PROFILE_PATH..."
    . $PROFILE_PATH
}

main() {
    for arg in "$@"; do
      case "$arg" in
        -h|--help)
          usage
          exit 0
          ;;
        *)
          ;;
      esac
    done

    install_nodenv_and_node
    skeet log -aa
}

main "$@"
} # this ensures the entire script is downloaded
