// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

// interface CloudflareEnv {
//   SKEET_AUTH_DB: D1Database
// }

declare global {
  // namespace NodeJS {
  //   interface ProcessEnv {
  //     [key: string]: string | undefined
  //     SKEET_AUTH_DB: D1Database
  //   }
  // }
}
export {}
